# Generated by Django 5.0.7 on 2024-07-09 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabecera', models.CharField(max_length=100)),
                ('distrito', models.SmallIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Distritos',
            },
        ),
        migrations.CreateModel(
            name='DistritoLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distrito_local', models.SmallIntegerField()),
                ('cabecera', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Distritos Locales',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.SmallIntegerField()),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Municipios',
            },
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.SmallIntegerField()),
                ('activa', models.BooleanField(default=True)),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bgd.distrito')),
                ('distrito_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bgd.distritolocal')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bgd.municipio')),
            ],
            options={
                'verbose_name_plural': 'Secciones',
            },
        ),
    ]
